# Fine-tune token classifier for social group mention detection and extraction

In this notebook, we use annotations from 

> Licht, Hauke, and Ronja Sczepanski. 2025. “Detecting Group Mentions in Political Rhetoric A Supervised Learning Approach.” British Journal of Political Science 55: e119. https://doi.org/10.1017/S0007123424000954.

to finetune a classifier capable of identifying and extracting phrases in texts that refer to social groups

<a target="_blank" href="https://colab.research.google.com/github/haukelicht/advanced_text_analysis/blob/main/notebooks/encoder_finetuning/finetune_token_classifier.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Background

span extraction:

- **task**: extract spans of words from a text that are mentions/indicators of a target concept
- **approaches**
    - supervised learning: token classification
    - prompting: prompt to respond with structured output of list of strings (verbatim extractions from input text, see Kasner et al, [2025](https://doi.org/10.48550/arXiv.2504.08697)) 

### examples

- **named entities** (place, organization, person)

    > "This year, **COMPTEXT** was in **Vienna**."

- **group mention** (social group, political group, etc.)

    > "**Labour** fights for **hard-working people**."

- **policy pledge**

    > "We will **lower taxes by 50%**."
    
- **valence attack** (i.e., criticism of political opponent's character/abilit/credibility)

    <!-- > "The Prime Minister **has not been honest with us**. -->

    > "The government has **betrayed the people** over and over again."


### token classification

![Illustration of token classification](../.assets/task_types-token_classification.svg){ height=50% }


- _token_-level classification: assign each token documents (e.g., sentences) categories
- single-label classification: assign each token to one and only one category

## methods papers and research applications

- Licht, Hauke, and Ronja Sczepanski. 2025. “Detecting Group Mentions in Political Rhetoric A Supervised Learning Approach.” British Journal of Political Science 55: e119. https://doi.org/10.1017/S0007123424000954.
- Kasner, Zdeněk, Vilém Zouhar, Patrícia Schmidtová, et al. 2025. “Large Language Models as Span Annotators.” arXiv:2504.08697. Version 1. Preprint, arXiv, April 11. https://doi.org/10.48550/arXiv.2504.08697.
- Klamm C, Rehbein I, Ponzetto SP. Our kind of people? Detecting populist references in political debates. 2023. *Findings of the Association for Computational Linguistics: EACL 2023*. 1227–1243. doi:[10.18653/v1/2023.findings-eacl.91](https://doi.org/10.18653/v1/2023.findings-eacl.91)
- Skorupa Parolin E, Hosseini MS, Hu Y, Khan L, Brandt PT, Osorio J, D'Orazio V. Multi-CoPED: A Multilingual Multi-Task Approach for Coding Political Event Data on Conflict and Mediation Domain. 2022. *Proceedings of the 2022 AAAI/ACM Conference on AI, Ethics, and Society (AIES '22)*. 700–711. doi:[10.1145/3514094.3534178](https://doi.org/10.1145/3514094.3534178)

## Setup

### Setup Colab (if using Colab)

**Note:** If running on Google Colab, make sure to use a GPU runtime (go to Runtime > Change runtime type, select "T4 GPU", and click save). See [this guide](https://github.com/haukelicht/advanced_text_analysis/blob/main/setup/setup_colab_runtime.md).

In [ ]:
# check if on colab
COLAB = True
try:
    import google.colab
except:
    COLAB=False

if COLAB:
    # shallow clone of current state of main branch 
    !git clone --branch main --single-branch --depth 1 --filter=blob:none https://github.com/haukelicht/advanced_text_analysis.git
    
    # install soft-seqeval (latest version)
    %pip install --no-build-isolation seqeval==1.2.2
    %pip install -q --upgrade --force-reinstall --no-deps git+https://github.com/haukelicht/soft-seqeval.git@main

In [ ]:
# set the PYTHONPATH so modules in `src/` can be found
from pathlib import Path
import sys

if COLAB:
    import sys
    sys.path.append("/content/advanced_text_analysis/")
else:
    base_path = Path('../..')
    sys.path.append(str(base_path.resolve()))

### Load required libraries

In [3]:
from pathlib import Path
import shutil

import numpy as np
import pandas as pd

import torch
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
    EarlyStoppingCallback,
    set_seed,
)

from soft_seqeval.metrics import compute_sequence_metrics

In [4]:
import os
from nltk.data import find as nltk_find
from nltk import download as nltk_download
nltk_res = ['punkt', 'punkt_tab']
for res in nltk_res:
    try:
        nltk_find(os.path.join('tokenizers', res))
    except LookupError:
        nltk_download(nltk_res)

In [5]:
import json
from pathlib import Path

from soft_seqeval.classes import LabeledSequence, Entities, Entity
from collections import OrderedDict

from typing import List, Dict, Any, Mapping, Union

def read_jsonlines_corpus(
    file: str, 
    id_field: str='id', 
    text_field: str='text', 
    annotations_field: str='label', 
    remove_unsure: bool=True,
    lang: str='english'
) -> Mapping[Union[str, int], LabeledSequence]:
    """Read a jsonlines corpus and return a dictionary of LabeledSequence objects.
    Args:
        file (str): Path to the jsonlines file.
        id_field (str): Name of the field containing the document ID.
        text_field (str): Name of the field containing the document text.
        annotations_field (str): Name of the field containing the annotations.
        remove_unsure (bool): Whether to remove annotations that end with 'unsure'.
        lang (str): Language of the documents.
    
    Returns:
        Mapping[Union[str, int], LabeledSequence]: A dictionary mapping document IDs to LabeledSequence objects.
    """
    with open(file, 'r') as f:
        data = [] 
        for line in f:
            try: 
                line = json.loads(line)
                data.append(line)
            except json.JSONDecodeError:
                pass
    
    documents = [
        # doc[text_field]:
        LabeledSequence(
            text=doc[text_field],
            entities=Entities([
                Entity(*lab) 
                for lab in doc[annotations_field] 
                if (not lab[2].lower().endswith('unsure') if remove_unsure else True)
            ]),
            id = doc[id_field],
            lang=lang
        )
        for doc in data
    ]
    
    return documents

In [6]:
MODEL_NAME = "answerdotai/ModernBERT-base"

In [7]:
device = 'cuda:0' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'mps'

In [8]:
SEED = 42

In [9]:
set_seed(SEED)

In [10]:
base_path = Path("/content/advanced_text_analysis/" if COLAB else "../../")

## Load and prepare the data

In [11]:
data_path = base_path / "data" / "labeled" / "licht_detecting_2025"

In [12]:
fp = data_path / "licht_detecting_2025-uk_manifestos-cleaned.jsonl"
if not fp.exists():
    url = "https://cta-text-datasets.s3.eu-central-1.amazonaws.com/labeled/licht_detecting_2025/licht_detecting_2025-uk_manifestos-cleaned.jsonl"
    df = pd.read_json(url, lines=True)
    fp.parent.mkdir(parents=True, exist_ok=True)
    df.to_json(fp, lines=True, orient='records', force_ascii=False)

In [13]:
corpus = read_jsonlines_corpus(fp)

In [15]:
corpus[2]

ef34613868b210a362e5bf0eee91fd35: "Neither Labour [other] nor Conservatives [other] are interested in changing our broken system, because it works to keep them in power."

In [16]:
from src.finetuning import split_data

data_splits = split_data(corpus, dev_size=0.1, test_size=0.15, seed=SEED, return_dict=True)

In [17]:
# from the annotations, get all entity "types" and construct a label2id mapping
#  where the labels are the IOB2-scheme for each entity type

types = list(set(ent.type for dataset in data_splits.values() for doc in dataset for ent in doc.entities))
scheme = ['O'] + ['I-'+t for t in types] + ['B-'+t for t in types]
label2id = {l: i for i, l in enumerate(scheme)}
id2label = {i: l for i, l in enumerate(scheme)}
NUM_LABELS = len(label2id)

label2id
# NOTE: the span-level annotations will be converted to token-level annotations using the IOB2 scheme.append
#       This means that 
#        - a word that are not part of any entity will be labeled as "O",
#        - a word at the beginning of a span will be labeled as "B-<entity_type>", and 
#        - a word inside a span will be labeled as "I-<entity_type>"

{'O': 0, 'I-other': 1, 'I-SG': 2, 'B-other': 3, 'B-SG': 4}

In [18]:
# NOTE: here we use the LabeledSequence instances to_labeled_tokens methods to convert 
#       the span-level annotations to token-level annotations
#       This method returns a LabeledTokens instance with the token-level annotations, 
#       which we then convert into a dictionary with fields 'tokens' and 'labels'.
data_splits = {
    s: [doc.to_labeled_tokens(label2id).to_dict() for doc in dataset]
    for s, dataset in data_splits.items()
}

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/soft_seqeval/classes/sequence.py:212: UserWarning: Language not provided. Required for NLTK-based tokenizer. Defaulting to "english".
  warnings.warn('Language not provided. Required for NLTK-based tokenizer. Defaulting to "english".')

In [19]:
# uncomment to show example
i = 2
for t, l in zip(data_splits['train'][i]['tokens'], data_splits['train'][i]['labels']):
    print(repr(t), '==>', id2label[l])

'Finally' ==> O
',' ==> O
' we' ==> O
' will' ==> O
' transform' ==> O
' our' ==> O
' mental' ==> B-other
' health' ==> I-other
' service' ==> I-other
' by' ==> O
' treating' ==> O
' it' ==> O
' with' ==> O
' the' ==> O
' same' ==> O
' urgency' ==> O
' as' ==> O
' physical' ==> O
' health' ==> O
'.' ==> O

In [20]:
from src.finetuning import create_token_classification_dataset
from datasets import DatasetDict

# use custom function defined above to convert corpus to a datasets.Dataset instance (used by transformers' Trainer below)
datasets = DatasetDict({
    s: create_token_classification_dataset(dataset)
    for s, dataset in data_splits.items()
})

In [21]:
datasets.num_rows

{'train': 6433, 'dev': 857, 'test': 1286}

In [22]:
datasets['train'][0]

{'tokens': ['Obviously',
  ' there',
  ' is',
  ' a',
  ' price',
  ' we',
  ' would',
  ' not',
  ' be',
  ' prepared',
  ' to',
  ' pay',
  '.'],
 'labels': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [23]:
from src.finetuning import preprocess_token_classification_dataset

# load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True, add_prefix_space=True)
assert isinstance(tokenizer, transformers.PreTrainedTokenizerFast)

# apply the custom function defined above to set subword tokens' labels to -100
# this is necessary because the tokenization may split a word into multiple subwords
datasets = datasets.map(lambda example: preprocess_token_classification_dataset(example, tokenizer=tokenizer), batched=True)

Map:   0%|          | 0/6433 [00:00<?, ? examples/s]

Map:   0%|          | 0/857 [00:00<?, ? examples/s]

Map:   0%|          | 0/1286 [00:00<?, ? examples/s]

In [24]:
# uncomment to show example
example = datasets['train'][2]
for t, l in zip(example['input_ids'], example['labels']):
    if t == tokenizer.pad_token_id:
        break
    print(l, '\t', repr(tokenizer.decode(t)))

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

-100 	 '[CLS]'
0 	 'Finally'
0 	 ','
0 	 ' we'
0 	 ' will'
0 	 ' transform'
0 	 ' our'
3 	 ' mental'
1 	 ' health'
1 	 ' service'
0 	 ' by'
0 	 ' treating'
0 	 ' it'
0 	 ' with'
0 	 ' the'
0 	 ' same'
0 	 ' urgency'
0 	 ' as'
0 	 ' physical'
0 	 ' health'
0 	 '.'
-100 	 '[SEP]'

In [25]:
# NOTE: after tokenization, text tokens are represented with their token IDs
#        so we can remove them from the dataset (need to load these to the GPU)
datasets = datasets.remove_columns(['tokens'])

## Prepare the model fine-tuning

In [26]:
from transformers import AutoConfig
# NOTE: the `model_init` function is used by the Trainer to initialize the model
#   and is called each time before training starts.
#  So we define it here to load the model from the Huggingface model hub
#   and set the number of labels to the number of unique labels in the dataset
#   and the label2id and id2label mappings
def model_init():
    config = AutoConfig.from_pretrained(MODEL_NAME)
    config.num_labels = NUM_LABELS
    config.label2id = label2id
    config.id2label = id2label
    return AutoModelForTokenClassification.from_pretrained(MODEL_NAME, config=config, device_map='auto')

In [27]:
# NOTE: we define a custom function for computing the fine-tuned model's performance in its 
#       prediction output for the dev or test set examples

# uncomment for example (with perfect scores)
y_true = datasets['test']['labels'][:25]
y_pred = datasets['test']['labels'][:25]

compute_sequence_metrics(y_true, y_pred, id2label, flatten_output=True)

{'seqeval-macro_f1': 1.0,
 'seqeval-macro_precision': 1.0,
 'seqeval-macro_recall': 1.0,
 'seqeval-micro_f1': 1.0,
 'seqeval-micro_precision': 1.0,
 'seqeval-micro_recall': 1.0,
 'seqeval-other_f1': 1.0,
 'seqeval-other_precision': 1.0,
 'seqeval-other_recall': 1.0,
 'seqeval-SG_f1': 1.0,
 'seqeval-SG_precision': 1.0,
 'seqeval-SG_recall': 1.0,
 'softseqeval-macro_f1': 1.0,
 'softseqeval-macro_precision': 1.0,
 'softseqeval-macro_recall': 1.0,
 'softseqeval-micro_f1': 1.0,
 'softseqeval-micro_precision': 1.0,
 'softseqeval-micro_recall': 1.0,
 'softseqeval-other_f1': 1.0,
 'softseqeval-other_precision': 1.0,
 'softseqeval-other_recall': 1.0,
 'softseqeval-SG_f1': 1.0,
 'softseqeval-SG_precision': 1.0,
 'softseqeval-SG_recall': 1.0,
 'doclevel-micro_precision': 1.0,
 'doclevel-micro_recall': 1.0,
 'doclevel-micro_f1': 1.0,
 'doclevel-other_precision': 1.0,
 'doclevel-other_recall': 1.0,
 'doclevel-other_f1': 1.0,
 'doclevel-SG_precision': 1.0,
 'doclevel-SG_recall': 1.0,
 'doclevel-SG_f1': 1.0,
 'wordlevel-accuracy': 1.0,
 'wordlevel-macro_f1': 1.0,
 'wordlevel-macro_precision': 1.0,
 'wordlevel-macro_recall': 1.0,
 'wordlevel-O_f1': 1.0,
 'wordlevel-O_precision': 1.0,
 'wordlevel-O_recall': 1.0,
 'wordlevel-other_f1': 1.0,
 'wordlevel-other_precision': 1.0,
 'wordlevel-other_recall': 1.0,
 'wordlevel-SG_f1': 1.0,
 'wordlevel-SG_precision': 1.0,
 'wordlevel-SG_recall': 1.0}

In [28]:
def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)
    # convert predictions and labels to list of lists of ints
    predictions = predictions.astype(int).tolist()
    labels = labels.astype(int).tolist()
    return compute_sequence_metrics(y_true=labels, y_pred=predictions, id2label=id2label, flatten_output=True)

In [29]:
# NOTE: at the beginning of the script, we have defined args.metric as the metric to be used for early stopping
#       and model selection among saved checkpoints after stopping
#       This metric must be available in the output of our `compute_metrics` function defined above
#       So let's check this
metric = "softseqeval-SG_f1"

ex = ['O', 'B-social group', 'I-social group', 'O']
scores = compute_sequence_metrics([ex], [ex], id2label, flatten_output=True)
if metric not in scores.keys():
    raise ValueError(f"Invalid metric: {metric}, valid metrics are: {', '.join(scores.keys())}")

### Define the training arguments

In [30]:
model_path = base_path / "models" / "licht_detecting_2025-group_mention_detector"

In [ ]:
out_dir = model_path
checkpoints_dir = out_dir / 'checkpoints'

training_args = TrainingArguments(
    
    # hyperparameters
    num_train_epochs=2, # TODO: increase this for actual training
    learning_rate=4e-5,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=2,
    per_device_eval_batch_size=32,
    weight_decay=0.3,
    optim='adamw_torch',
    
    # when to evaluate
    eval_strategy='epoch',
    # how to select "best" model
    do_eval=bool('dev' in datasets),
    metric_for_best_model="seqeval-macro_f1",
    load_best_model_at_end=True,
    # when to save
    save_strategy='epoch',
    save_total_limit=2 if 'dev' in datasets else None, # don't save all model checkpoints
    # where to store results
    output_dir=checkpoints_dir,
    
    # logging
    logging_strategy='epoch',
    
    # reproducibility
    seed=SEED,
    data_seed=SEED,
    full_determinism=True
)

In [ ]:
# build callbacks
callbacks = []
if 'dev' in datasets:
    callbacks.append(EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.03))

### Create the trainer

In [32]:
trainer = Trainer(
    model_init=model_init,
    args=training_args,
    train_dataset=datasets['train'].select(range(2000)),
    eval_dataset=datasets['dev'] if 'dev' in datasets else None,
    processing_class=tokenizer,
    data_collator=DataCollatorForTokenClassification(tokenizer),
    compute_metrics=compute_metrics,
    callbacks=callbacks
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForTokenClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Train

In [33]:
print('Training ...')
train_hist = trainer.train()

Training ...

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForTokenClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.
/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

### Evaluate

In [34]:
# apply the best model loaded after finishing training to the test set
print('Evaluating ...')
test_res = trainer.evaluate(datasets['test'], metric_key_prefix='test')

Evaluating ...

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

[transformers] early stopping required metric_for_best_model, but did not find eval_seqeval-macro_f1 so early stopping is disabled

In [35]:
# create a more nice-to-look-at output
out = pd.DataFrame(test_res, index=['value']).T
out = out.reset_index().rename(columns={'index': 'cat'})
out[['set', 'scheme', 'metric']] = out.cat.str.split('_', expand=True)
out = out[out.metric.notnull()]
out[['scheme', 'type']] = out.scheme.str.split('-', expand=True)
out = out.drop(columns=['set', 'cat'])
out = out[['scheme', 'type', 'metric', 'value']]
out = out.pivot(index=['type', 'scheme', ], columns='metric', values='value')
keys = [
    (typ, scheme)
    for typ in types
    for scheme in ['seqeval', 'softseqeval', 'wordlevel', 'doclevel']
]
out.loc[keys, :]
# NOTE: train more epochs and/or with the full train data and scores will improve

metric                   f1  precision    recall
type  scheme
other seqeval      0.659429   0.634066  0.686905
      softseqeval  0.695614   0.719016  0.690925
      wordlevel    0.808688   0.837853  0.781485
      doclevel     0.898911   0.898911  0.898911
SG    seqeval      0.576978   0.541892  0.616923
      softseqeval  0.641652   0.661943  0.649078
      wordlevel    0.763363   0.790423  0.738095
      doclevel     0.908243   0.908243  0.908243

### Inference

In [36]:
from datasets import Dataset

from transformers import pipeline
from transformers.pipelines.pt_utils import KeyDataset

from tqdm import tqdm

We'll use the transformer's `pipeline` for inference (i.e., predicting spans in unlabeled data).

Specifically, we use the **NER** (named entity recognition) task and pass the fine-tuned model from the trainer.

In [37]:
extractor = pipeline(
    task='ner',
    model=trainer.model,
    tokenizer=tokenizer,
    aggregation_strategy='simple'
)

In [38]:
fields = ['id', 'text']
df = pd.DataFrame([{f: doc[f] for f in fields} for doc in data_splits['test']])

In [39]:
# apply the extractor to the dataset
pred_ents = [p for p in extractor(df['text'].tolist(), batch_size=32)]

In [40]:
pred_ents[0]

[{'entity_group': 'other',
  'score': np.float32(0.73036295),
  'word': ' the EU',
  'start': 60,
  'end': 67},
 {'entity_group': 'SG',
  'score': np.float32(0.94685197),
  'word': ' the British people',
  'start': 105,
  'end': 124}]

For each text in the list of texts taken from `docs`, we get a list of dictionaries, here called `pred_ents`.

Each item in `pred_ents` is a dictionary with the following fields:

- start: character start index of the entity in the text
- end: character end index of the entity in the text
- score: confidence score of the prediction
- word: the text of the entity
- entity_group: the entity type (e.g., 'social group')

Let's use convert these annotations into one `Entities` instance and create a new `LabeledSequence` instance from this information for each text:

In [41]:
from soft_seqeval.classes import Entity, Entities
from soft_seqeval.classes import LabeledSequence
from copy import deepcopy

def pipeline_output_to_entities(pred) -> Entities:
    """Take output from the NER pipeline and convert to Entities instance"""
    ents = []
    for ent in pred:
        ent = deepcopy(ent)
        if ent['word'][0] == ' ':
            ent['start'] += 1
        if ent['word'][-1] == ' ':
            ent['end'] -= 1
        ents.append(Entity(ent['start'], ent['end'], ent['entity_group']))
    return Entities(ents)

# iterate over the documents and predicted annotations to create a list of LabeledSequence instances
preds = [
    LabeledSequence(text=doc['text'], entities=pipeline_output_to_entities(pred), id=doc['id'], lang='english')
    for (_, doc), pred in zip(df.iterrows(), pred_ents)
]

In [42]:
# look at first 10 examples
preds[:10]

[efb8de4509cba09231ccd6450da031f5: "We do not accept that either a “hard” Brexit or an exit from the EU [other] without a deal is in the interests of the British people [SG].",
 38c2699bab9e041b0a091545515928e2: "Use our campaign for a better environment to provide the basis of secured employment, eg in pollution control and in waste recycling.",
 1940d2626700c0a531da90c521d88d59: "Second, we will avoid further Labour [other] stealth taxes by reducing government [other] borrowing.",
 620609561fd750a7bdb171be603e8d48: "We are seen today as a people with [SG] integrity, resolve and the will to succeed.",
 490babb970db4affed2fafd43ed5492c: "The Northern Ireland Executive [other] has also undertaken a significant programme of public sector reform with major changes in education administration [other], the health service [other] and in local government [other].",
 8c57a4c133001c8bdc7e0ed7054791c3: "The same backward-looking approach has prevented them from responding to the major world changes of the last decade.",
 fffbd5247cd457c40739ddc52a74773e: "We are asking Local Education Authorities [other] not to make sales of school [other] playing fields in future unless there is no evidence of long-term need.",
 c346a98d950b6d03f55e553df597c38d: "Britain deserves better than the Conservatives [other]’ reckless approach to complex global challenges or the outsourcing of UK foreign policy to US President Donald Trump.",
 1d6965d6d14b3aeb5db7aaadf1913dbf: "Europe [SG] isn't working in the way this country and Europe need.",
 f5de049bb264b1fe253a035f54ade816: "Maintain properly equipped Regular forces [other] together with reserve forces [other] - including the Territorial Army [other] - suitable reorganised for their supporting roles."]

## Finally

#### Delete intermediate checkpoints and log files

In [43]:
# finally: clean up
if checkpoints_dir.exists():
    shutil.rmtree(checkpoints_dir)

#### Save the best model (if desired)

In [44]:
trainer.save_model(out_dir)
tokenizer.save_pretrained(out_dir)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('../../models/licht_detecting_2025-group_mention_detector/tokenizer_config.json',
 '../../models/licht_detecting_2025-group_mention_detector/tokenizer.json')

### clean up

In [45]:
# free the GPU and remove large objects
import gc
trainer = trainer.model.to('cpu')
del trainer, tokenizer, data_splits, datasets
gc.collect()

385

In [46]:
# after exercise: remove saved model (to free disk space)
# NOTE: only do when running this notebook as an exercise
if model_path.exists():
    shutil.rmtree(model_path)